### ISSUE TITLE
Invenio props are generated inside the metadata section, not on top-level

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder#13]
```yaml
model:
  oarepo:use: invenio
  properties:
    title:
      type: fulltext+keyword
```

**Comment by mesemus** [comment]
fixed, correct usage is:

```yaml
model:
  oarepo:use: invenio
  properties:
    metadata:
      properties:
        title:
          type: fulltext+keyword
```
