### ISSUE TITLE
Check if field: "blah" works with oarepo-model-builder-multilingual

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder#143]
```
subject:
      type: multilingual
      required: true
      label.cs: Klíčová slova
      label.en: Keywords
      ui:
        detail: string
        marshmallow:
          field: MultilingualLocalizedUIField()
          imports:
            - import: oarepo_runtime.i18n.ui_schema.MultilingualLocalizedUIField
```

seems to be generated incorrectly
