### ISSUE TITLE
Sorting support

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder#38]
Add support for autogenerated sorters.

Suggestion for simple sorters:

```yaml
model:
  ...
    creator:
      oarepo:sortable: true
    creator2:
      oarepo:sortable:
        key: creator2
        direction: asc|desc
```

And for complex sorts:

```yaml
oarepo:sort:
  bytitle:
  - key: title.sort
     direction: asc
  - key: creator
     direction: asc
```

Nested fields should have the correct mapping generated automatically
