### ISSUE TITLE
EDTFDateString namiesto Date

### ISSUE THREAD

**Issue by jurajtrappl** [oarepo/oarepo-model-builder#75]
Pouzil som nasledujuce metadata:

```yaml
model:
  properties:
    metadata:
      properties:
        title:
          type: fulltext
        updated:
          type: date
          required: true
          oarepo:sample:
            faker: iso8601
            skip: false

oarepo:use:
  - invenio
```

Trieda `{Nazov}MetadataSchema` po vygenerovani:

```yaml
class ThesisMetadataSchema(
    ma.Schema,
):
    """ThesisMetadataSchema schema."""

    title = ma_fields.String()

    updated = ma_fields.Date(required=True)
```

Problem je, ze po vygenerovani pozadujeme pre field `updated` typ `EDTFDateString` (from marshmallow_utils.fields import EDTFDateString). 

Poprosim upravit. Zaroven upravit aj generovanie sample dat.
